        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 11 23:58:33 2025
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE GET_RELATIVEDEFORMATIONGRADIENT__genmod
          INTERFACE 
            SUBROUTINE GET_RELATIVEDEFORMATIONGRADIENT(IEL,IPOINT,ICON,B&
     &,DISP,NDOFEX,RELATIVEDEFORMATIONGRADIENT,IPATCH)
              USE MODMPMDATA
              USE MODMESHINFO
              INTEGER(KIND=4), INTENT(IN) :: IEL
              INTEGER(KIND=4), INTENT(IN) :: IPOINT
              INTEGER(KIND=4), INTENT(IN) :: ICON(ELEMENTNODES,NURBS%   &
     &MAXIMUM_NEL_NURBS)
              REAL(KIND=8), INTENT(IN) :: B(NVECTOR,ELEMENTNODES)
              REAL(KIND=8), INTENT(IN) :: DISP(COUNTERS%N)
              INTEGER(KIND=4), INTENT(IN) :: NDOFEX(                    &
     &NUMBEROFGLOBALCONTROLPOINTSUNIQUEMULTIPATCH+1)
              REAL(KIND=8), INTENT(OUT) :: RELATIVEDEFORMATIONGRADIENT( &
     &NDIM,NDIM)
              INTEGER(KIND=4), INTENT(IN) :: IPATCH
            END SUBROUTINE GET_RELATIVEDEFORMATIONGRADIENT
          END INTERFACE 
        END MODULE GET_RELATIVEDEFORMATIONGRADIENT__genmod
