        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 18 14:29:09 2025
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE LOAD3D__genmod
          INTERFACE 
            SUBROUTINE LOAD3D(RLOAD,NDOF,COORD,NINT,NNOD,ILOADCON,      &
     &ELEMENTUPONWHICHLOADISAPPLIED,ILOADSYSTEM,IPATCH,                 &
     &NXIKNOTENTRIES_SIDESPECIFIC,XIKNOTENTRIES_SIDESPECIFIC,           &
     &NETAKNOTENTRIES_SIDESPECIFIC,ETAKNOTENTRIES_SIDESPECIFIC)
              USE MODELEMENTEVALUATION
              INTEGER(KIND=4), INTENT(IN) ::                            &
     &NETAKNOTENTRIES_SIDESPECIFIC
              INTEGER(KIND=4), INTENT(IN) :: NXIKNOTENTRIES_SIDESPECIFIC
              INTEGER(KIND=4), INTENT(IN) :: NNOD
              INTEGER(KIND=4), INTENT(IN) :: NINT
              REAL(KIND=8), INTENT(INOUT) :: RLOAD(COUNTERS%SUM_NODTOT* &
     &NDOFL)
              INTEGER(KIND=4) :: NDOF(COUNTERS%SUM_NODTOT)
              REAL(KIND=8), INTENT(IN) :: COORD(COUNTERS%SUM_NODTOT,    &
     &NVECTOR)
              INTEGER(KIND=4) :: ILOADCON(NNOD)
              INTEGER(KIND=4), INTENT(IN) ::                            &
     &ELEMENTUPONWHICHLOADISAPPLIED
              INTEGER(KIND=4), INTENT(IN) :: ILOADSYSTEM
              INTEGER(KIND=4), INTENT(IN) :: IPATCH
              REAL(KIND=8), INTENT(IN) :: XIKNOTENTRIES_SIDESPECIFIC(   &
     &NXIKNOTENTRIES_SIDESPECIFIC)
              REAL(KIND=8), INTENT(IN) :: ETAKNOTENTRIES_SIDESPECIFIC(  &
     &NETAKNOTENTRIES_SIDESPECIFIC)
            END SUBROUTINE LOAD3D
          END INTERFACE 
        END MODULE LOAD3D__genmod
