### Anura3D_2021 ###	
*####################################################################################
$$SOLID_PHASE
*if(GenData(write_solid_data_ID,int)==100)
mean_effective_stress 1
deviatoric_stress 1
volumetric_strain 1
deviatoric_strain 1
incremental_volumetric_strain 1
incremental_deviatoric_strain 1
mass 1
density 1
weight 1
displacement 1
velocity 1
acceleration 1
body_force 1
external_force 1
global_position 1
local_position 1
*end if
*if(GenData(write_solid_data_ID,int)==101)
mean_effective_stress *GenData(mean_effective_stress)
deviatoric_stress *GenData(deviatoric_stress)
volumetric_strain *GenData(volumetric_strain)
deviatoric_strain *GenData(deviatoric_strain)
incremental_volumetric_strain *GenData(incremental_volumetric_strain)
incremental_deviatoric_strain *GenData(incremental_deviatoric_strain)
mass *GenData(mass)
density *GenData(density)
weight *GenData(weight)
displacement *GenData(displacement)
velocity *GenData(velocity)
acceleration *GenData(acceleration)
body_force *GenData(body_force)
external_force *GenData(external_force)
global_position *GenData(global_position)
local_position *GenData(local_position)
*end if
*if(GenData(write_solid_data_ID,int)==102)
mean_effective_stress 0
deviatoric_stress 0
volumetric_strain 0
deviatoric_strain 0
incremental_volumetric_strain 0
incremental_deviatoric_strain 0
mass 0
density 0
weight 0
displacement 0
velocity 0
acceleration 0
body_force 0
external_force 0
global_position 0
local_position 0
*end if
*####################################################################################
$$LIQUID_PHASE
*if(GenData(write_liquid_data_ID,int)==100)
mean_pressure 1
volumetric_strain 1
mass 1
density 1
weight 1
displacement 1
velocity 1 
acceleration 1 
body_force 1 
external_force 1
global_position 1
local_position 1
*end if
*if(GenData(write_liquid_data_ID,int)==101)
mean_pressure *GenData(mean_pressure_)
volumetric_strain *GenData(volumetric_strain_)
mass *GenData(mass_)
density *GenData(density_)
weight *GenData(weight_)
displacement *GenData(displacement_)
velocity *GenData(velocity_)
acceleration *GenData(acceleration_)
body_force *GenData(body_force_)
external_force *GenData(external_force_)
global_position *GenData(global_position_)
local_position *GenData(local_position_)
*end if
*if(GenData(write_liquid_data_ID,int)==102)
mean_pressure 0
volumetric_strain 0
mass 0
density 0
weight 0
displacement 0
velocity 0 
acceleration 0 
body_force 0 
external_force 0
global_position 0
local_position 0
*end if
*####################################################################################
$$MIXTURE
*if(GenData(write_mixture_data_ID,int)==100)
porosity 1
body_force 1
*end if
*if(GenData(write_mixture_data_ID,int)==101)
porosity *GenData(porosity__)
body_force *GenData(body_force__)
*end if
*if(GenData(write_mixture_data_ID,int)==102)
porosity 0
body_force 0
*end if
*####################################################################################
$$GENERAL_DATA
*if(GenData(write_general_data_ID,int)==100)
damping 1
element_ID 1
entity_ID 1
integration_weight 1
material_ID 1
material_point_ID 1
*end if
*if(GenData(write_general_data_ID,int)==101)
damping *GenData(damping___)
element_ID *GenData(element_ID___)
entity_ID *GenData(entity_ID___)
integration_weight *GenData(integration_weight___)
material_ID *GenData(material_ID___)
material_point_ID *GenData(material_point_ID___)
*end if
*if(GenData(write_general_data_ID,int)==102)
damping 0
element_ID 0
entity_ID 0
integration_weight 0
material_ID 0
material_point_ID 0
*end if
*####################################################################################
$$MATERIAL_DATA
*if(GenData(write_material_data_ID,int)==100)
state_variable_1 1 
state_variable_2 1 
state_variable_3 1 
state_variable_4 1 
state_variable_5 1 
state_variable_6 1 
state_variable_7 1 
state_variable_8 1 
state_variable_9 1 
state_variable_10 1 
state_variable_11 1 
state_variable_12 1
state_variable_13 1
state_variable_14 1
state_variable_15 1
state_variable_16 1
state_variable_17 1
state_variable_18 1
state_variable_19 1
state_variable_20 1
state_variable_21 1
state_variable_22 1
state_variable_23 1
state_variable_24 1
state_variable_25 1
state_variable_26 1
state_variable_27 1
state_variable_28 1
state_variable_29 1
state_variable_30 1
state_variable_31 1
state_variable_32 1
state_variable_33 1 
state_variable_34 1
state_variable_35 1
state_variable_36 1
state_variable_37 1
state_variable_38 1
state_variable_39 1
state_variable_40 1
state_variable_41 1
state_variable_42 1
state_variable_43 1
state_variable_44 1
state_variable_45 1
state_variable_46 1
state_variable_47 1
state_variable_48 1
state_variable_49 1
state_variable_50 1
*end if
*if(GenData(write_material_data_ID,int)==101)
state_variable_1 *GenData(state_variable_1)
state_variable_2 *GenData(state_variable_2)
state_variable_3 *GenData(state_variable_3)
state_variable_4 *GenData(state_variable_4)
state_variable_5 *GenData(state_variable_5)
state_variable_6 *GenData(state_variable_6)
state_variable_7 *GenData(state_variable_7)
state_variable_8 *GenData(state_variable_8)
state_variable_9 *GenData(state_variable_9)
state_variable_10 *GenData(state_variable_10)
state_variable_11 *GenData(state_variable_11)
state_variable_12 *GenData(state_variable_12)
state_variable_13 *GenData(state_variable_13)
state_variable_14 *GenData(state_variable_14)
state_variable_15 *GenData(state_variable_15)
state_variable_16 *GenData(state_variable_16)
state_variable_17 *GenData(state_variable_17)
state_variable_18 *GenData(state_variable_18)
state_variable_19 *GenData(state_variable_19)
state_variable_20 *GenData(state_variable_20)
state_variable_21 *GenData(state_variable_21)
state_variable_22 *GenData(state_variable_22)
state_variable_23 *GenData(state_variable_23)
state_variable_24 *GenData(state_variable_24)
state_variable_25 *GenData(state_variable_25)
state_variable_26 *GenData(state_variable_26)
state_variable_27 *GenData(state_variable_27)
state_variable_28 *GenData(state_variable_28)
state_variable_29 *GenData(state_variable_29)
state_variable_30 *GenData(state_variable_30)
state_variable_31 *GenData(state_variable_31)
state_variable_32 *GenData(state_variable_32)
state_variable_33 *GenData(state_variable_33)
state_variable_34 *GenData(state_variable_34)
state_variable_35 *GenData(state_variable_35)
state_variable_36 *GenData(state_variable_36)
state_variable_37 *GenData(state_variable_37)
state_variable_38 *GenData(state_variable_38)
state_variable_39 *GenData(state_variable_39)
state_variable_40 *GenData(state_variable_40)
state_variable_41 *GenData(state_variable_41)
state_variable_42 *GenData(state_variable_42)
state_variable_43 *GenData(state_variable_43)
state_variable_44 *GenData(state_variable_44)
state_variable_45 *GenData(state_variable_45)
state_variable_46 *GenData(state_variable_46)
state_variable_47 *GenData(state_variable_47)
state_variable_48 *GenData(state_variable_48)
state_variable_49 *GenData(state_variable_49)
state_variable_50 *GenData(state_variable_50)
*end if
*if(GenData(write_material_data_ID,int)==102)
state_variable_1 0 
state_variable_2 0 
state_variable_3 0 
state_variable_4 0 
state_variable_5 0 
state_variable_6 0 
state_variable_7 0 
state_variable_8 0 
state_variable_9 0 
state_variable_10 0 
state_variable_11 0 
state_variable_12 0
state_variable_13 0
state_variable_14 0
state_variable_15 0
state_variable_16 0
state_variable_17 0
state_variable_18 0
state_variable_19 0
state_variable_20 0
state_variable_21 0
state_variable_22 0
state_variable_23 0
state_variable_24 0
state_variable_25 0
state_variable_26 0
state_variable_27 0
state_variable_28 0
state_variable_29 0
state_variable_30 0
state_variable_31 0
state_variable_32 0
state_variable_33 0 
state_variable_34 0
state_variable_35 0
state_variable_36 0
state_variable_37 0
state_variable_38 0
state_variable_39 0
state_variable_40 0
state_variable_41 0
state_variable_42 0
state_variable_43 0
state_variable_44 0
state_variable_45 0
state_variable_46 0
state_variable_47 0
state_variable_48 0
state_variable_49 0
state_variable_50 0
*end if
$$END_OF_FILE